class ExamCenter {
  String name;
  String email;
  String mobilePhone;
  String countryCode;
  bool isAgree;
  String otp;
  String mpin;
  String centerType;
  String typeOfCenter;
  String centerName;
  String centerDescription;
  int capacity;
  int countryId;
  int stateId;
  int cityId;
  String localAreaName;
  String postalAddress;
  double addressLat;
  double addressLong;
  String nearbyLandmark;
  bool isLiftAvailable;
  String nearestRailwayStation;
  String nearestBusStop;
  double distanceFromRailwayStation;
  double distanceFromBusStop;
  String nearestMetroStation;
  double distanceFromMetroStation;
  String nearestAirport;
  double distanceFromAirport;
  String pointOfContact;
  String contactPhoneNumber;
  String contactAlternatePhoneNumber;
  String contactEmail;
  String superintendentName;
  String superintendentNumber;
  String superintendentEmail;
  String assistantManagerName;
  String assistantManagerPhoneNumber;
  String assistantManagerEmail;
  String emergencyLandlineNumber;
  String emergencyPhoneNumber;

  List<String> centerEntrances;
  List<String> labPhotos;
  List<String> mainGateImages;
  List<String> serverRoomImages;
  List<String> observerRoomImages;
  List<String> upsGeneratorImages;
  String walkthroughVideo;

  List<int> floorNumber;
  List<int> totalComputers;
  List<String> windowGeneration;
  List<String> monitorType;
  List<String> operatingSystem;
  List<String> ram;
  List<String> hdd;
  List<String> ethernetCompany;
  List<String> switchCategory;
  List<int> noOfEachEthernetPorts;
  List<String> ethernetCompanyOther;

  int totalNumberOfLab;
  int totalNumberOfSystem;
  bool? labAreConnectToSingleNetwork;
  int totalNetwork;
  bool partitionInEachLab;
  bool acInEachLab;
  int howManyFireExtinguisherInEachLab;

  bool? isNetworkPrinterAvailabel;
  bool isThereProjectorInEachLab;
  bool isThereSoundSystemInEachLab;
  bool isThereALockerFacilityInLab;
  bool isThereADrinkingWaterFacilityInLab;

  String primaryInfrastructure;
  String primaryIspConnectType;
  double primaryIspSpeed;
  String primaryInternetSpeedUnit;

  String secondaryInfrastructure;
  String secondaryIspConnectType;
  double secondaryIspSpeed;
  String secondaryInternetSpeedUnit;

  bool isGeneratorBackup;
  double generatorBackupCapacity;
  double generatorFuelTankCapacity;
  bool upsBackup;
  double upsBackupTime;
  int totalNoOfConnection;
  int backupHours;
  int backupMinutes;

  String beneficiaryName;
  String bankName;
  String bankAccountNumber;
  String bankIfsc;
  String panNumber;
  String gstNumber;
  int gstStateCode;
  String uidaiNumber;
  String msmeNumber;
  bool hasGst;
  bool hasMsme;

  ExamCenter({
    required this.name,
    required this.email,
    required this.mobilePhone,
    required this.countryCode,
    required this.isAgree,
    required this.otp,
    required this.mpin,
    required this.centerType,
    required this.typeOfCenter,
    required this.centerName,
    required this.centerDescription,
    required this.capacity,
    required this.countryId,
    required this.stateId,
    required this.cityId,
    required this.localAreaName,
    required this.postalAddress,
    required this.addressLat,
    required this.addressLong,
    required this.nearbyLandmark,
    required this.isLiftAvailable,
    required this.nearestRailwayStation,
    required this.nearestBusStop,
    required this.distanceFromRailwayStation,
    required this.distanceFromBusStop,
    required this.nearestMetroStation,
    required this.distanceFromMetroStation,
    required this.nearestAirport,
    required this.acInEachLab,
    required this.distanceFromAirport,
    required this.pointOfContact,
    required this.contactPhoneNumber,
    required this.contactAlternatePhoneNumber,
    required this.contactEmail,
    required this.superintendentName,
    required this.superintendentNumber,
    required this.superintendentEmail,
    required this.assistantManagerName,
    required this.assistantManagerPhoneNumber,
    required this.assistantManagerEmail,
    required this.emergencyLandlineNumber,
    required this.emergencyPhoneNumber,
    required this.centerEntrances,
    required this.labPhotos,
    required this.mainGateImages,
    required this.serverRoomImages,
    required this.observerRoomImages,
    required this.upsGeneratorImages,
    required this.walkthroughVideo,
    required this.floorNumber,
    required this.totalComputers,
    required this.windowGeneration,
    required this.monitorType,
    required this.operatingSystem,
    required this.ram,
    required this.hdd,
    required this.ethernetCompany,
    required this.switchCategory,
    required this.noOfEachEthernetPorts,
    required this.ethernetCompanyOther,
    required this.totalNumberOfLab,
    required this.totalNumberOfSystem,
    required this.labAreConnectToSingleNetwork,
    required this.totalNetwork,
    required this.partitionInEachLab,
    required this.isNetworkPrinterAvailabel,
    required this.isThereProjectorInEachLab,
    required this.isThereSoundSystemInEachLab,
    required this.howManyFireExtinguisherInEachLab,
    required this.isThereALockerFacilityInLab,
    required this.isThereADrinkingWaterFacilityInLab,
    required this.primaryInfrastructure,
    required this.primaryIspConnectType,
    required this.primaryIspSpeed,
    required this.primaryInternetSpeedUnit,
    required this.secondaryInfrastructure,
    required this.secondaryIspConnectType,
    required this.secondaryIspSpeed,
    required this.secondaryInternetSpeedUnit,
    required this.isGeneratorBackup,
    required this.generatorBackupCapacity,
    required this.generatorFuelTankCapacity,
    required this.upsBackup,
    required this.upsBackupTime,
    required this.totalNoOfConnection,
    required this.backupHours,
    required this.backupMinutes,
    required this.beneficiaryName,
    required this.bankName,
    required this.bankAccountNumber,
    required this.bankIfsc,
    required this.panNumber,
    required this.gstNumber,
    required this.gstStateCode,
    required this.uidaiNumber,
    required this.msmeNumber,
    required this.hasGst,
    required this.hasMsme,
  });

  Map<String, dynamic> toJson() => {
    "name": name,
    "email": email,
    "mobile_phone": mobilePhone,
    "country_code": countryCode,
    "is_agree": isAgree,
    "otp": otp,
    "mpin": mpin,
    "center_type": centerType,
    "type_of_center": typeOfCenter,
    "center_name": centerName,
    "center_description": centerDescription,
    "capacity": capacity,
    "country_id": countryId,
    "state_id": stateId,
    "city_id": cityId,
    "local_area_name": localAreaName,
    "postal_address": postalAddress,
    "address_lat": addressLat,
    "address_long": addressLong,
    "nearby_landmark": nearbyLandmark,
    "is_lift_available": isLiftAvailable == true ? "Yes" : "No",
    "nearest_railway_station": nearestRailwayStation,
    "nearest_bus_stop": nearestBusStop,
    "distance_from_railway_station": distanceFromRailwayStation,
    "distance_from_bus_stop": distanceFromBusStop,
    "nearest_metro_station": nearestMetroStation,
    "distance_from_metro_station": distanceFromMetroStation,
    "nearest_airport": nearestAirport,
    "distance_from_airport": distanceFromAirport,
    "point_of_contact": pointOfContact,
    "contact_phone_number": contactPhoneNumber,
    "contact_alternate_phone_number": contactAlternatePhoneNumber,
    "contact_email": contactEmail,
    "superintendent_name": superintendentName,
    "superintendent_number": superintendentNumber,
    "superintendent_email": superintendentEmail,
    "assistant_manager_name": assistantManagerName,
    "assistant_manager_phone_number": assistantManagerPhoneNumber,
    "assistant_manager_email": assistantManagerEmail,
    "emergency_landline_number": emergencyLandlineNumber,
    "emergency_phone_number": emergencyPhoneNumber,
    "center_entrances": centerEntrances,
    "lab_photos": labPhotos,
    "main_gate_images": mainGateImages,
    "server_room_images": serverRoomImages,
    "observer_room_images": observerRoomImages,
    "ups_generator_images": upsGeneratorImages,
    "walkthrough_video": walkthroughVideo,
    "floor_number": floorNumber,
    "total_computers": totalComputers,
    "window_generation": windowGeneration,
    "monitor_type": monitorType,
    "operating_system": operatingSystem,
    "ram": ram,
    "hdd": hdd,
    "ethernet_company": ethernetCompany,
    "switch_category": switchCategory,
    "no_of_each_ethernet_ports": noOfEachEthernetPorts,
    "ethernet_company_other": ethernetCompanyOther,
    "total_number_of_lab": totalNumberOfLab,
    "total_number_of_system": totalNumberOfSystem,
    "lab_are_connect_to_single_network": labAreConnectToSingleNetwork,
    "total_network": totalNetwork,
    "partition_in_each_lab": partitionInEachLab,
    "is_network_printer_availabel": isNetworkPrinterAvailabel,
    "is_there_projector_in_each_lab": isThereProjectorInEachLab,
    "is_there_sound_system_in_each_lab": isThereSoundSystemInEachLab,
    "how_many_fire_extinguisher_in_each_lab": howManyFireExtinguisherInEachLab,
    "is_there_a_locker_facility_in_lab": isThereALockerFacilityInLab,
    "is_there_a_drinking_water_facility_in_lab": isThereADrinkingWaterFacilityInLab,
    "primary_infrastructure": primaryInfrastructure,
    "primary_isp_connect_type": primaryIspConnectType,
    "primary_isp_speed": primaryIspSpeed,
    "ac_in_each_lab": acInEachLab,
    "primary_internet_speed_unit": primaryInternetSpeedUnit,
    "secondary_infrastructure": secondaryInfrastructure,
    "secondary_isp_connect_type": secondaryIspConnectType,
    "secondary_isp_speed": secondaryIspSpeed,
    "secondary_internet_speed_unit": secondaryInternetSpeedUnit,
    "is_generator_backup": isGeneratorBackup,
    "generator_backup_capacity": generatorBackupCapacity,
    "generator_fuel_tank_capacity": generatorFuelTankCapacity,
    "ups_backup": upsBackup,
    "ups_backup_time": upsBackupTime,
    "total_no_of_connection": totalNoOfConnection,
    "backup_hours": backupHours,
    "backup_minutes": backupMinutes,
    "beneficiary_name": beneficiaryName,
    "bank_name": bankName,
    "bank_account_number": bankAccountNumber,
    "bank_ifsc": bankIfsc,
    "pannumber": panNumber,
    "gst_number": gstNumber,
    "gst_state_code": gstStateCode,
    "uidai_number": uidaiNumber,
    "msme_number": msmeNumber,
    "has_gst": hasGst,
    "has_msme": hasMsme,

  };
}
